server:
  port: 8055
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=Asia/Shanghai
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.yemou.oa.pojo
#  configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl